server:
  port: 7901
spring:
  application:
    name: account-info-a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blank1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group

logging:
  level:
    root: info
    org.hibernate: INFO
    org.hibernate.type.desciptor.sql.BasicBinder: trace
    org.hibernate.type.desciptor.sql.BasicExtractor: trace
    com.itmuch: debug
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}